kind: pipeline
name: default

platform:
  os: linux
  arch: arm

workspace:
  base: /go
  path: filestash

clone:
  depth: 1

steps:
- name: build_prepare
  image: alpine:latest
  depends_on: [ clone ]
  commands:
  - mkdir -p ./dist/data/state/
  - cp -R config ./dist/data/state/
  - mkdir -p ./filestash/data/state/
  - cp -R config ./filestash/data/state/

- name: build_frontend
  image: node:12-alpine
  depends_on: [ build_prepare ]
  commands:
  - apk add make git python2 build-base > /dev/null
  - npm install --silent
  - make build_frontend
  - cp -R ./dist/data/public ./filestash/data/public

- name: build_backend
  image: golang:1.12-stretch
  depends_on: [ build_prepare ]
  environment:
    CGO_LDFLAGS_ALLOW: "-fopenmp"
    GO111MODULE: "on"
  commands:
  - apt-get update > /dev/null && apt-get install -y libglib2.0-dev curl make > /dev/null
  - make build_init
  - make build_backend
  - timeout 1 ./dist/filestash || true
  - cp dist/filestash filestash/
  - chmod -R o+r+w+x ./dist/data

- name: release_prepare
  image: debian:stable-slim
  depends_on: [ build_frontend, build_backend ]
  commands:
  - chmod -R o-r-w-x- ./filestash
  - tar -cf filestash_Linux-armhf.tar ./filestash

- name: publish
  image: plugins/github-release
  depends_on: [ release_prepare ]
  when:
    event:
      - tag
  settings:
    api_key:
      from_secret: github_token
    files: "*.tar"
